export type AuditAction =
  | 'ADMIN_CREATED_BLOG'
  | 'ADMIN_UPDATED_BLOG'
  | 'ADMIN_PUBLISHED_BLOG'
  | 'ADMIN_ARCHIVED_BLOG'
  | 'ADMIN_DELETED_BLOG'
  | 'ADMIN_ACCEPTED_ORDER'
  | 'ADMIN_REJECTED_ORDER'
  | 'ADMIN_REQUESTED_CORRECTION'
  | 'ADMIN_COMPLETED_ORDER'
  | 'ADMIN_UPDATED_ORDER_STATUS'
  | 'DOCUMENT_SCHEDULED_FOR_DELETION'
  | 'DOCUMENT_DELETED'
  | 'DOCUMENT_DELETION_FAILED';

export type AuditTargetType = 'order' | 'blog' | 'document';
